<a href="https://colab.research.google.com/github/MOMO46-sust/First-Repo/blob/main/momoes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
array= np.random.randint(5,16,size=(2,4))
print('2d array:\n',array)

2d array:
 [[ 6  7 14 14]
 [12  7 13  7]]


In [4]:
transpose=array.T
print('transpose of the array;\n',transpose)

transpose of the array;
 [[ 6 12]
 [ 7  7]
 [14 13]
 [14  7]]


In [5]:
sum_elements=np.sum(array)
print('sum of all elements:',sum_elements)

sum of all elements: 80


In [7]:
indices=np.argwhere(array > 10)
print(indices)

[[0 2]
 [0 3]
 [1 0]
 [1 2]]


In [13]:
#create a text file name 'notes.txt'
import os
with open ("notes.txt","w") as file:
  file.write('')
#append text ,read and print the content
with open("notes.txt","a") as file:
  file.write('programmimg is an essential skill in todays world.')
with open('notes.txt','r') as file:
  content=file.read()
print('file contents:',content)
#delete a file if it exists
if os.path.exists('notes.txt'):
  os.remove('notes.txt')
  print('file deleted')
else:
  print('File does not exists')



file contents: programmimg is an essential skill in todays world.
file deleted
